# Generated by Django 4.2.2 on 2023-07-04 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ('pub_date', 'id'), 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('pub_date', 'id'), 'verbose_name': 'Новости', 'verbose_name_plural': 'Новости'},
        ),
    ]
